# Generated by Django 5.2.7 on 2025-11-12 20:08

import django.db.models.deletion
import flights.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, verbose_name='Modelo')),
                ('registration_number', models.CharField(max_length=10, unique=True, verbose_name='Matrícula')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad Total')),
            ],
            options={
                'verbose_name': 'Avión',
                'verbose_name_plural': 'Aviones',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Teléfono')),
                ('identification_number', models.CharField(max_length=50, null=True, unique=True, verbose_name='DNI / Pasaporte')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
            ],
            options={
                'verbose_name': 'Pasajero',
                'verbose_name_plural': 'Pasajeros',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10, unique=True, verbose_name='Número de Vuelo')),
                ('origin', models.CharField(max_length=100, verbose_name='Origen')),
                ('destination', models.CharField(max_length=100, verbose_name='Destino')),
                ('departure_time', models.DateTimeField(verbose_name='Hora de Salida')),
                ('arrival_time', models.DateTimeField(verbose_name='Hora de Llegada')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='flights.aircraft', verbose_name='Avión Asignado')),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5, verbose_name='Número de Asiento')),
                ('is_window_seat', models.BooleanField(default=False, verbose_name='Asiento de Ventanilla')),
                ('seat_class', models.CharField(choices=[('ECONOMY', 'Económica'), ('BUSINESS', 'Negocios'), ('FIRST', 'Primera Clase')], max_length=10, verbose_name='Clase de Asiento')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Base')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.aircraft', verbose_name='Avión')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'unique_together': {('aircraft', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_code', models.CharField(default=flights.models.generate_reservation_code, max_length=6, unique=True, verbose_name='Código de Reserva')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reserva')),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='flights.flight', verbose_name='Vuelo')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='flights.passenger', verbose_name='Pasajero')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='flights.seat', verbose_name='Asiento')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'unique_together': {('flight', 'seat')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=50, unique=True, verbose_name='Código de Boleto')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio del Boleto')),
                ('is_checked_in', models.BooleanField(default=False, verbose_name='Check-in Realizado')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='flights.reservation', verbose_name='Reserva Asociada')),
            ],
        ),
    ]
