# Generated by Django 5.0.4 on 2025-11-12 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_flight_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seat",
            options={
                "ordering": ["seat_number"],
                "verbose_name": "Asiento",
                "verbose_name_plural": "Asientos",
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("confirmed", "Confirmada"),
                    ("canceled", "Cancelada"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="flights.reservation",
                verbose_name="Reserva",
            ),
        ),
    ]
