# Generated by Django 5.2.7 on 2025-11-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='model_name',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='identification_number',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='columns',
            field=models.IntegerField(default=6, verbose_name='Columnas'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='rows',
            field=models.IntegerField(default=10, verbose_name='Filas'),
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('SCH', 'Programado'), ('ACT', 'Activo / En Vuelo'), ('DEL', 'Retrasado'), ('CAN', 'Cancelado'), ('ARR', 'Aterrizado / Finalizado')], default='SCH', max_length=3, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='apellido',
            field=models.CharField(default='SIN APELLIDO', max_length=100, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passenger',
            name='documento',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Número de Documento'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01', verbose_name='Fecha de Nacimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passenger',
            name='nombre',
            field=models.CharField(default='SIN NOMBRE', max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passenger',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI (Documento Nacional de Identidad)'), ('PAS', 'Pasaporte'), ('OTR', 'Otro')], default='OTR', max_length=3, verbose_name='Tipo de Documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='capacity',
            field=models.IntegerField(verbose_name='Capacidad Total de Asientos'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='registration_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Base'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email de Contacto'),
        ),
    ]
