# Generated by Django 5.2.7 on 2025-11-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
