# Generated by Django 5.2.7 on 2025-11-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_reservation_is_confirmed_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Base'),
        ),
    ]
