# Generated by Django 5.2.7 on 2025-11-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_seat_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='identification_number',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='DNI / Pasaporte'),
        ),
    ]
