# Generated by Django 5.2.7 on 2025-11-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_passenger_identification_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
